# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20170624_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='appendtime',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
