# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20170701_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotedeal',
            old_name='user',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='promote',
            name='shoptypeID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotedeal',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Order'),
        ),
    ]
